from typing import Literal

CHAT_INTENT = Literal[
	"GENERAL_CHAT",
	"FAILED_TRANSACTION",
	"UNSUPPORTED_COMPLAIN"
]

MAIN_GRAPH_STATUS = Literal[
	"INTENT_CHECK",
	"USER_GATHERING",
	"USER_VERIF",
	"SUBGRAPH",
	"COMPLETED",
]

SOP1_GRAPH_STATUS = Literal[
	"TRANSACTION_GATHERING",
	"TRANSACTION_VERIF",
	"GOOD_FAITH_CHECK",
	"COMPLETED",
]

TRX_STATUS = Literal[
	"FAILED",
	"PENDING",
	"COMPLETED"
]